import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB


try:
    # Read the 10,000-row dataset generated by your factory script
    df = pd.read_csv('expenses.csv')
except FileNotFoundError:
    print("\n[ERROR] Could not find 'expenses.csv'!")
    print("Please run 'python generate_data.py' first to generate your dataset.\n")
    exit()

# Drop any accidental blank rows to ensure data integrity
df = df.dropna(subset=['Description', 'Category'])

X_train = df['Description']
y_train = df['Category']



# ==========================================
# PHASE 2: TRAINING THE NAIVE BAYES MODEL
# ==========================================

# Using English stop words to ignore neutral connectors like 'and', 'for', 'to'
vectorizer = CountVectorizer(stop_words='english')
X_train_vectorized = vectorizer.fit_transform(X_train)

model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

print("AI Model Trained successfully across all categories!")
print("-" * 60)

# ==========================================
# PHASE 3: MULTI-CATEGORY PREDICTION LOOP
# ==========================================

print("Type 'quit' at any time to exit the program.\n")

while True:
    user_input = input("Type an expense description: ").strip()

    if not user_input:
        continue

    if user_input.lower() == 'quit':
        print("Goodbye!")
        break 

    # Convert the user input text into the numerical format the AI expects
    user_vector = vectorizer.transform([user_input])

    # Calculate probabilities across all 10 categories secretly in the background
    probabilities = model.predict_proba(user_vector)[0]
    
    # Pair the category names with their corresponding scores
    category_scores = list(zip(model.classes_, probabilities))
    
    # Sort the list so the highest confidence scores are at the top
    category_scores.sort(key=lambda x: x[1], reverse=True)

    print("\n--> Classified Category:")
    
    found_match = False
    
    # Check the top 2 highest scoring categories
    for category, score in category_scores[:2]:
        # With 10 categories, any score above 12% indicates a strong keyword match
        if score > 0.12:
            print(f"    * {category}")
            found_match = True
            
    if not found_match:
        print("    * Unknown Expense")
        
    print("-" * 40)